# Generated by Django 5.2.9 on 2026-08-20 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100, verbose_name='Crop Name')),
                ('crop_type', models.CharField(choices=[('Cereal / Grain', 'Cereal / Grain'), ('Pulse / Legume', 'Pulse / Legume'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Cash Crop', 'Cash Crop'), ('Oilseed', 'Oilseed'), ('Fodder', 'Fodder'), ('Spice', 'Spice')], default='Cereal / Grain', max_length=50, verbose_name='Crop Type')),
                ('season', models.CharField(choices=[('Kharif (Monsoon)', 'Kharif (Monsoon)'), ('Rabi (Winter)', 'Rabi (Winter)'), ('Zaid (Summer)', 'Zaid (Summer)'), ('Year-Round', 'Year-Round')], default='Kharif (Monsoon)', max_length=50, verbose_name='Season')),
                ('farm_area', models.DecimalField(decimal_places=2, help_text='Total land area in acres', max_digits=10, verbose_name='Farm Area (Acres)')),
                ('planting_date', models.DateField(verbose_name='Planting Date')),
                ('expected_harvest_date', models.DateField(verbose_name='Expected Harvest Date')),
                ('status', models.CharField(choices=[('Planted', 'Planted'), ('Growing', 'Growing'), ('Ready to Harvest', 'Ready to Harvest'), ('Harvested', 'Harvested')], default='Planted', max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes & Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('farm_location', models.CharField(max_length=255, verbose_name='Farm Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
