# Generated by Django 5.2.9 on 2026-08-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0002_emailverificationotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tip Title')),
                ('category', models.CharField(choices=[('Soil Preparation', 'Soil Preparation'), ('Irrigation', 'Irrigation'), ('Fertilizer', 'Fertilizer & Nutrition'), ('Pest Control', 'Pest & Disease Control'), ('Crop Rotation', 'Crop Rotation'), ('Organic Farming', 'Organic Farming')], default='Soil Preparation', max_length=100, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Tip Description')),
                ('level', models.CharField(default='Essential', max_length=50, verbose_name='Importance / Badge Level')),
                ('icon', models.CharField(default='fa-seedling', max_length=50, verbose_name='FontAwesome Icon Class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tips/', verbose_name='Tip Image (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farming Tip',
                'verbose_name_plural': 'Farming Tips',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action Type')),
                ('details', models.TextField(blank=True, verbose_name='Event Details')),
                ('icon', models.CharField(default='fa-circle-info', max_length=50, verbose_name='Icon Class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
