# Generated by Django 5.2.9 on 2026-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_farmingtip_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='region',
            field=models.CharField(choices=[('Saurashtra', 'Saurashtra (Rajkot, Junagadh, Amreli, Jamnagar, Bhavnagar, etc.)'), ('North Gujarat', 'North Gujarat (Banaskantha, Patan, Mehsana, Sabarkantha, Aravalli)'), ('Central Gujarat', 'Central Gujarat (Ahmedabad, Anand, Kheda, Vadodara, Panchmahal)'), ('South Gujarat', 'South Gujarat (Surat, Navsari, Valsad, Bharuch, Narmada, Tapi, Dang)'), ('Kutch', 'Kutch (Bhuj, Mandvi, Anjar, Rapar, Nakhatrana)')], default='Saurashtra', max_length=100, verbose_name='Gujarat Agricultural Region'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='district',
            field=models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Amreli', 'Amreli'), ('Anand', 'Anand'), ('Aravalli', 'Aravalli'), ('Banaskantha', 'Banaskantha'), ('Bharuch', 'Bharuch'), ('Bhavnagar', 'Bhavnagar'), ('Botad', 'Botad'), ('Chhota Udepur', 'Chhota Udepur'), ('Dahod', 'Dahod'), ('Dang', 'Dang'), ('Devbhumi Dwarka', 'Devbhumi Dwarka'), ('Gandhinagar', 'Gandhinagar'), ('Gir Somnath', 'Gir Somnath'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Kheda', 'Kheda'), ('Kutch', 'Kutch'), ('Mahisagar', 'Mahisagar'), ('Mehsana', 'Mehsana'), ('Morbi', 'Morbi'), ('Narmada', 'Narmada'), ('Navsari', 'Navsari'), ('Panchmahal', 'Panchmahal'), ('Patan', 'Patan'), ('Porbandar', 'Porbandar'), ('Rajkot', 'Rajkot'), ('Sabarkantha', 'Sabarkantha'), ('Surat', 'Surat'), ('Surendranagar', 'Surendranagar'), ('Tapi', 'Tapi'), ('Vadodara', 'Vadodara'), ('Valsad', 'Valsad')], default='Ahmedabad', max_length=100, verbose_name='Gujarat District'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='taluka',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Taluka / Block'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(choices=[('Cereal / Grain', 'Cereal / Grain (Wheat, Bajra, Maize, Rice)'), ('Cash Crop', 'Cash Crop (Cotton, Sugarcane, Tobacco)'), ('Oilseed', 'Oilseed (Groundnut, Castor, Sesame, Mustard)'), ('Spice', 'Spice / Seed (Cumin / Jeera, Fennel, Coriander)'), ('Pulse / Legume', 'Pulse / Legume (Chickpea, Tuver, Green Gram)'), ('Vegetable', 'Vegetable (Onion, Tomato, Potato, Chili)'), ('Fruit', 'Fruit (Mango, Pomegranate, Banana, Papaya)'), ('Fodder', 'Fodder')], default='Cash Crop', max_length=50, verbose_name='Crop Type'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Village / Farm Location'),
        ),
        migrations.AlterField(
            model_name='farmingtip',
            name='category',
            field=models.CharField(choices=[('Soil Preparation', 'Soil Preparation'), ('Irrigation', 'Irrigation & Drip Technology'), ('Water Management', 'Water Conservation & Management'), ('Fertilizer', 'Fertilizer & Soil Nutrition'), ('Pest Control', 'Pest & Disease Control'), ('Crop Rotation', 'Crop Rotation'), ('Organic Farming', 'Organic Farming (Prakrutik Kheti)'), ('Monsoon Farming', 'Monsoon Farming (Kharif Season)'), ('Rabi Farming', 'Winter Farming (Rabi Season)'), ('Kharif Farming', 'Kharif Crops Management')], default='Soil Preparation', max_length=100, verbose_name='Category'),
        ),
    ]
