# Generated by Django 5.2.9 on 2026-08-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Agro-Climatic Region')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts (Gujarat)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read'), ('Replied', 'Replied')], default='Unread', max_length=20, verbose_name='Message Status'),
        ),
        migrations.AddField(
            model_name='crop',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='crop',
            name='taluka',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Taluka'),
        ),
        migrations.AddField(
            model_name='crop',
            name='village',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Village / Farm Name'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planting_date',
            field=models.DateField(verbose_name='Planting / Sowing Date'),
        ),
        migrations.AlterField(
            model_name='farmingtip',
            name='category',
            field=models.CharField(choices=[('Crop Management', '🌾 Crop Management'), ('Irrigation', '💧 Irrigation & Drip Technology'), ('Soil Management', '🌱 Soil Management & Health Cards'), ('Monsoon Farming', '🌧️ Monsoon Farming (Kharif Season)'), ('Summer Farming', '☀️ Summer Farming (Zaid Season)'), ('Winter Farming', '❄️ Winter Farming (Rabi Season)'), ('Pest Management', '🐛 Pest & Disease Management'), ('Harvesting', '🌾 Harvesting & Storage'), ('Micro Irrigation', '💧 Micro Irrigation (GGRC Drip & Sprinkler)'), ('Organic Farming', '🌿 Organic Farming (Prakrutik Kheti)')], default='Crop Management', max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='crop',
            name='district_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farming.district', verbose_name='District Reference'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='district_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farming.district', verbose_name='District Reference'),
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taluka Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='farming.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Taluka',
                'verbose_name_plural': 'Talukas (Gujarat)',
                'ordering': ['district__name', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='taluka_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farming.taluka', verbose_name='Taluka Reference'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='taluka_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farming.taluka', verbose_name='Taluka Reference'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Village Name')),
                ('pincode', models.CharField(blank=True, default='', max_length=10, verbose_name='Pincode (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='farming.taluka', verbose_name='Taluka')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages (Gujarat)',
                'ordering': ['taluka__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='village_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farming.village', verbose_name='Village Reference'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='village_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='farming.village', verbose_name='Village Reference'),
        ),
    ]
